// Copyright 2020-2021 Team RelicFrog
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: api_usr_invite_code.proto

package api_usr_invite_code

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usr_invite_code_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_usr_invite_code_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_usr_invite_code_proto_rawDescGZIP(), []int{0}
}

type UserInviteCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MetaCode       string                 `protobuf:"bytes,2,opt,name=meta_code,json=metaCode,proto3" json:"meta_code,omitempty"`
	MetaForAppRole string                 `protobuf:"bytes,3,opt,name=meta_for_app_role,json=metaForAppRole,proto3" json:"meta_for_app_role,omitempty"`
	IsFixture      bool                   `protobuf:"varint,4,opt,name=is_fixture,json=isFixture,proto3" json:"is_fixture,omitempty"`
	IsDeleted      bool                   `protobuf:"varint,5,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	IsUsed         bool                   `protobuf:"varint,6,opt,name=is_used,json=isUsed,proto3" json:"is_used,omitempty"`
	MetaValidFrom  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=meta_valid_from,json=metaValidFrom,proto3" json:"meta_valid_from,omitempty"`
	MetaValidTo    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=meta_valid_to,json=metaValidTo,proto3" json:"meta_valid_to,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *UserInviteCode) Reset() {
	*x = UserInviteCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usr_invite_code_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInviteCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInviteCode) ProtoMessage() {}

func (x *UserInviteCode) ProtoReflect() protoreflect.Message {
	mi := &file_api_usr_invite_code_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInviteCode.ProtoReflect.Descriptor instead.
func (*UserInviteCode) Descriptor() ([]byte, []int) {
	return file_api_usr_invite_code_proto_rawDescGZIP(), []int{1}
}

func (x *UserInviteCode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserInviteCode) GetMetaCode() string {
	if x != nil {
		return x.MetaCode
	}
	return ""
}

func (x *UserInviteCode) GetMetaForAppRole() string {
	if x != nil {
		return x.MetaForAppRole
	}
	return ""
}

func (x *UserInviteCode) GetIsFixture() bool {
	if x != nil {
		return x.IsFixture
	}
	return false
}

func (x *UserInviteCode) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *UserInviteCode) GetIsUsed() bool {
	if x != nil {
		return x.IsUsed
	}
	return false
}

func (x *UserInviteCode) GetMetaValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.MetaValidFrom
	}
	return nil
}

func (x *UserInviteCode) GetMetaValidTo() *timestamppb.Timestamp {
	if x != nil {
		return x.MetaValidTo
	}
	return nil
}

func (x *UserInviteCode) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserInviteCode) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UserInviteCode) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type UserInviteCodeFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MetaCode       string `protobuf:"bytes,1,opt,name=meta_code,json=metaCode,proto3" json:"meta_code,omitempty"`
	MetaForAppRole string `protobuf:"bytes,2,opt,name=meta_for_app_role,json=metaForAppRole,proto3" json:"meta_for_app_role,omitempty"`
}

func (x *UserInviteCodeFilter) Reset() {
	*x = UserInviteCodeFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usr_invite_code_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInviteCodeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInviteCodeFilter) ProtoMessage() {}

func (x *UserInviteCodeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_usr_invite_code_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInviteCodeFilter.ProtoReflect.Descriptor instead.
func (*UserInviteCodeFilter) Descriptor() ([]byte, []int) {
	return file_api_usr_invite_code_proto_rawDescGZIP(), []int{2}
}

func (x *UserInviteCodeFilter) GetMetaCode() string {
	if x != nil {
		return x.MetaCode
	}
	return ""
}

func (x *UserInviteCodeFilter) GetMetaForAppRole() string {
	if x != nil {
		return x.MetaForAppRole
	}
	return ""
}

type CreateInviteCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteCode *UserInviteCode `protobuf:"bytes,1,opt,name=inviteCode,proto3" json:"inviteCode,omitempty"`
}

func (x *CreateInviteCodeReq) Reset() {
	*x = CreateInviteCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usr_invite_code_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateInviteCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteCodeReq) ProtoMessage() {}

func (x *CreateInviteCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_usr_invite_code_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteCodeReq.ProtoReflect.Descriptor instead.
func (*CreateInviteCodeReq) Descriptor() ([]byte, []int) {
	return file_api_usr_invite_code_proto_rawDescGZIP(), []int{3}
}

func (x *CreateInviteCodeReq) GetInviteCode() *UserInviteCode {
	if x != nil {
		return x.InviteCode
	}
	return nil
}

type CreateInviteCodeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteCode *UserInviteCode `protobuf:"bytes,1,opt,name=inviteCode,proto3" json:"inviteCode,omitempty"`
}

func (x *CreateInviteCodeRes) Reset() {
	*x = CreateInviteCodeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usr_invite_code_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateInviteCodeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteCodeRes) ProtoMessage() {}

func (x *CreateInviteCodeRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_usr_invite_code_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteCodeRes.ProtoReflect.Descriptor instead.
func (*CreateInviteCodeRes) Descriptor() ([]byte, []int) {
	return file_api_usr_invite_code_proto_rawDescGZIP(), []int{4}
}

func (x *CreateInviteCodeRes) GetInviteCode() *UserInviteCode {
	if x != nil {
		return x.InviteCode
	}
	return nil
}

type GetInviteCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetInviteCodeReq) Reset() {
	*x = GetInviteCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usr_invite_code_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInviteCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInviteCodeReq) ProtoMessage() {}

func (x *GetInviteCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_usr_invite_code_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInviteCodeReq.ProtoReflect.Descriptor instead.
func (*GetInviteCodeReq) Descriptor() ([]byte, []int) {
	return file_api_usr_invite_code_proto_rawDescGZIP(), []int{5}
}

func (x *GetInviteCodeReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetInviteCodeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteCode *UserInviteCode `protobuf:"bytes,1,opt,name=inviteCode,proto3" json:"inviteCode,omitempty"`
}

func (x *GetInviteCodeRes) Reset() {
	*x = GetInviteCodeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usr_invite_code_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInviteCodeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInviteCodeRes) ProtoMessage() {}

func (x *GetInviteCodeRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_usr_invite_code_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInviteCodeRes.ProtoReflect.Descriptor instead.
func (*GetInviteCodeRes) Descriptor() ([]byte, []int) {
	return file_api_usr_invite_code_proto_rawDescGZIP(), []int{6}
}

func (x *GetInviteCodeRes) GetInviteCode() *UserInviteCode {
	if x != nil {
		return x.InviteCode
	}
	return nil
}

type UpdateInviteCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteCode *UserInviteCode `protobuf:"bytes,1,opt,name=inviteCode,proto3" json:"inviteCode,omitempty"`
}

func (x *UpdateInviteCodeReq) Reset() {
	*x = UpdateInviteCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usr_invite_code_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateInviteCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInviteCodeReq) ProtoMessage() {}

func (x *UpdateInviteCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_usr_invite_code_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInviteCodeReq.ProtoReflect.Descriptor instead.
func (*UpdateInviteCodeReq) Descriptor() ([]byte, []int) {
	return file_api_usr_invite_code_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateInviteCodeReq) GetInviteCode() *UserInviteCode {
	if x != nil {
		return x.InviteCode
	}
	return nil
}

type UpdateInviteCodeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteCode *UserInviteCode `protobuf:"bytes,1,opt,name=inviteCode,proto3" json:"inviteCode,omitempty"`
}

func (x *UpdateInviteCodeRes) Reset() {
	*x = UpdateInviteCodeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usr_invite_code_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateInviteCodeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInviteCodeRes) ProtoMessage() {}

func (x *UpdateInviteCodeRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_usr_invite_code_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInviteCodeRes.ProtoReflect.Descriptor instead.
func (*UpdateInviteCodeRes) Descriptor() ([]byte, []int) {
	return file_api_usr_invite_code_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateInviteCodeRes) GetInviteCode() *UserInviteCode {
	if x != nil {
		return x.InviteCode
	}
	return nil
}

type DeleteInviteCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteInviteCodeReq) Reset() {
	*x = DeleteInviteCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usr_invite_code_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteInviteCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInviteCodeReq) ProtoMessage() {}

func (x *DeleteInviteCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_usr_invite_code_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInviteCodeReq.ProtoReflect.Descriptor instead.
func (*DeleteInviteCodeReq) Descriptor() ([]byte, []int) {
	return file_api_usr_invite_code_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteInviteCodeReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteInviteCodeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteInviteCodeRes) Reset() {
	*x = DeleteInviteCodeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usr_invite_code_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteInviteCodeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInviteCodeRes) ProtoMessage() {}

func (x *DeleteInviteCodeRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_usr_invite_code_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInviteCodeRes.ProtoReflect.Descriptor instead.
func (*DeleteInviteCodeRes) Descriptor() ([]byte, []int) {
	return file_api_usr_invite_code_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteInviteCodeRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListFilteredInviteCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter *UserInviteCodeFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *ListFilteredInviteCodeReq) Reset() {
	*x = ListFilteredInviteCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usr_invite_code_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFilteredInviteCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilteredInviteCodeReq) ProtoMessage() {}

func (x *ListFilteredInviteCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_usr_invite_code_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilteredInviteCodeReq.ProtoReflect.Descriptor instead.
func (*ListFilteredInviteCodeReq) Descriptor() ([]byte, []int) {
	return file_api_usr_invite_code_proto_rawDescGZIP(), []int{11}
}

func (x *ListFilteredInviteCodeReq) GetFilter() *UserInviteCodeFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListFilteredInviteCodeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteCode *UserInviteCode `protobuf:"bytes,1,opt,name=inviteCode,proto3" json:"inviteCode,omitempty"`
}

func (x *ListFilteredInviteCodeRes) Reset() {
	*x = ListFilteredInviteCodeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usr_invite_code_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFilteredInviteCodeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilteredInviteCodeRes) ProtoMessage() {}

func (x *ListFilteredInviteCodeRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_usr_invite_code_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilteredInviteCodeRes.ProtoReflect.Descriptor instead.
func (*ListFilteredInviteCodeRes) Descriptor() ([]byte, []int) {
	return file_api_usr_invite_code_proto_rawDescGZIP(), []int{12}
}

func (x *ListFilteredInviteCodeRes) GetInviteCode() *UserInviteCode {
	if x != nil {
		return x.InviteCode
	}
	return nil
}

type ListInviteCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListInviteCodeReq) Reset() {
	*x = ListInviteCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usr_invite_code_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListInviteCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInviteCodeReq) ProtoMessage() {}

func (x *ListInviteCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_usr_invite_code_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInviteCodeReq.ProtoReflect.Descriptor instead.
func (*ListInviteCodeReq) Descriptor() ([]byte, []int) {
	return file_api_usr_invite_code_proto_rawDescGZIP(), []int{13}
}

type ListInviteCodeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteCode *UserInviteCode `protobuf:"bytes,1,opt,name=inviteCode,proto3" json:"inviteCode,omitempty"`
}

func (x *ListInviteCodeRes) Reset() {
	*x = ListInviteCodeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usr_invite_code_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListInviteCodeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInviteCodeRes) ProtoMessage() {}

func (x *ListInviteCodeRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_usr_invite_code_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInviteCodeRes.ProtoReflect.Descriptor instead.
func (*ListInviteCodeRes) Descriptor() ([]byte, []int) {
	return file_api_usr_invite_code_proto_rawDescGZIP(), []int{14}
}

func (x *ListInviteCodeRes) GetInviteCode() *UserInviteCode {
	if x != nil {
		return x.InviteCode
	}
	return nil
}

type VersionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VersionReq) Reset() {
	*x = VersionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usr_invite_code_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionReq) ProtoMessage() {}

func (x *VersionReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_usr_invite_code_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionReq.ProtoReflect.Descriptor instead.
func (*VersionReq) Descriptor() ([]byte, []int) {
	return file_api_usr_invite_code_proto_rawDescGZIP(), []int{15}
}

type VersionRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *VersionRes) Reset() {
	*x = VersionRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usr_invite_code_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRes) ProtoMessage() {}

func (x *VersionRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_usr_invite_code_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRes.ProtoReflect.Descriptor instead.
func (*VersionRes) Descriptor() ([]byte, []int) {
	return file_api_usr_invite_code_proto_rawDescGZIP(), []int{16}
}

func (x *VersionRes) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_api_usr_invite_code_proto protoreflect.FileDescriptor

var file_api_usr_invite_code_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x5f, 0x75, 0x73, 0x72, 0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x61, 0x70, 0x69,
	0x5f, 0x75, 0x73, 0x72, 0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0xf4, 0x03, 0x0a, 0x0e, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x29, 0x0a, 0x11, 0x6d, 0x65,
	0x74, 0x61, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x61, 0x70, 0x70, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6d, 0x65, 0x74, 0x61, 0x46, 0x6f, 0x72, 0x41, 0x70,
	0x70, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x66, 0x69, 0x78, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x46, 0x69, 0x78,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x75, 0x73, 0x65, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x55, 0x73, 0x65, 0x64, 0x12, 0x42, 0x0a, 0x0f,
	0x6d, 0x65, 0x74, 0x61, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x0d, 0x6d, 0x65, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x46, 0x72, 0x6f, 0x6d,
	0x12, 0x3e, 0x0a, 0x0d, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x74,
	0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x0b, 0x6d, 0x65, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x54, 0x6f,
	0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x22, 0x5e, 0x0a, 0x14, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43,
	0x6f, 0x64, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x74,
	0x61, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x29, 0x0a, 0x11, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x66,
	0x6f, 0x72, 0x5f, 0x61, 0x70, 0x70, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x6d, 0x65, 0x74, 0x61, 0x46, 0x6f, 0x72, 0x41, 0x70, 0x70, 0x52, 0x6f, 0x6c,
	0x65, 0x22, 0x5a, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x43, 0x0a, 0x0a, 0x69, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61,
	0x70, 0x69, 0x5f, 0x75, 0x73, 0x72, 0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x5a, 0x0a,
	0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x12, 0x43, 0x0a, 0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x75,
	0x73, 0x72, 0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0a, 0x69,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x57, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x73, 0x12, 0x43, 0x0a, 0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x75, 0x73, 0x72, 0x5f,
	0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0a, 0x69, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x5a, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x43, 0x0a,
	0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x75, 0x73, 0x72, 0x5f, 0x69, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x22, 0x5a, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x12, 0x43, 0x0a, 0x0a, 0x69, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x61, 0x70, 0x69, 0x5f, 0x75, 0x73, 0x72, 0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x25,
	0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x5e, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x65, 0x64, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x41, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x75, 0x73, 0x72, 0x5f, 0x69, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x60, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x65, 0x64, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x73, 0x12, 0x43, 0x0a, 0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x75, 0x73,
	0x72, 0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0a, 0x69, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74,
	0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x22, 0x58, 0x0a,
	0x11, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x73, 0x12, 0x43, 0x0a, 0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x75, 0x73, 0x72,
	0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0a, 0x69, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x0c, 0x0a, 0x0a, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x22, 0x26, 0x0a, 0x0a, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x32, 0xe0, 0x05,
	0x0a, 0x15, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x66, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x28, 0x2e, 0x61, 0x70,
	0x69, 0x5f, 0x75, 0x73, 0x72, 0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x75, 0x73, 0x72, 0x5f,
	0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x12,
	0x5d, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x75, 0x73, 0x72, 0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x75, 0x73,
	0x72, 0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x12, 0x66,
	0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x75, 0x73, 0x72, 0x5f, 0x69, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x28, 0x2e, 0x61,
	0x70, 0x69, 0x5f, 0x75, 0x73, 0x72, 0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x12, 0x66, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x28, 0x2e, 0x61, 0x70, 0x69,
	0x5f, 0x75, 0x73, 0x72, 0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x75, 0x73, 0x72, 0x5f, 0x69,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x12, 0x63,
	0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x73, 0x12, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x75, 0x73, 0x72, 0x5f, 0x69, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x5f,
	0x75, 0x73, 0x72, 0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x73, 0x30, 0x01, 0x12, 0x7b, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x65, 0x64, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x2e,
	0x2e, 0x61, 0x70, 0x69, 0x5f, 0x75, 0x73, 0x72, 0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x65,
	0x64, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x2e,
	0x2e, 0x61, 0x70, 0x69, 0x5f, 0x75, 0x73, 0x72, 0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x65,
	0x64, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x30, 0x01,
	0x12, 0x4e, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1f,
	0x2e, 0x61, 0x70, 0x69, 0x5f, 0x75, 0x73, 0x72, 0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a,
	0x1f, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x75, 0x73, 0x72, 0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x42, 0x17, 0x5a, 0x15, 0x2e, 0x3b, 0x61, 0x70, 0x69, 0x5f, 0x75, 0x73, 0x72, 0x5f, 0x69, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_usr_invite_code_proto_rawDescOnce sync.Once
	file_api_usr_invite_code_proto_rawDescData = file_api_usr_invite_code_proto_rawDesc
)

func file_api_usr_invite_code_proto_rawDescGZIP() []byte {
	file_api_usr_invite_code_proto_rawDescOnce.Do(func() {
		file_api_usr_invite_code_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_usr_invite_code_proto_rawDescData)
	})
	return file_api_usr_invite_code_proto_rawDescData
}

var file_api_usr_invite_code_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_usr_invite_code_proto_goTypes = []interface{}{
	(*Empty)(nil),                     // 0: api_usr_invite_code.Empty
	(*UserInviteCode)(nil),            // 1: api_usr_invite_code.UserInviteCode
	(*UserInviteCodeFilter)(nil),      // 2: api_usr_invite_code.UserInviteCodeFilter
	(*CreateInviteCodeReq)(nil),       // 3: api_usr_invite_code.CreateInviteCodeReq
	(*CreateInviteCodeRes)(nil),       // 4: api_usr_invite_code.CreateInviteCodeRes
	(*GetInviteCodeReq)(nil),          // 5: api_usr_invite_code.GetInviteCodeReq
	(*GetInviteCodeRes)(nil),          // 6: api_usr_invite_code.GetInviteCodeRes
	(*UpdateInviteCodeReq)(nil),       // 7: api_usr_invite_code.UpdateInviteCodeReq
	(*UpdateInviteCodeRes)(nil),       // 8: api_usr_invite_code.UpdateInviteCodeRes
	(*DeleteInviteCodeReq)(nil),       // 9: api_usr_invite_code.DeleteInviteCodeReq
	(*DeleteInviteCodeRes)(nil),       // 10: api_usr_invite_code.DeleteInviteCodeRes
	(*ListFilteredInviteCodeReq)(nil), // 11: api_usr_invite_code.ListFilteredInviteCodeReq
	(*ListFilteredInviteCodeRes)(nil), // 12: api_usr_invite_code.ListFilteredInviteCodeRes
	(*ListInviteCodeReq)(nil),         // 13: api_usr_invite_code.ListInviteCodeReq
	(*ListInviteCodeRes)(nil),         // 14: api_usr_invite_code.ListInviteCodeRes
	(*VersionReq)(nil),                // 15: api_usr_invite_code.VersionReq
	(*VersionRes)(nil),                // 16: api_usr_invite_code.VersionRes
	(*timestamppb.Timestamp)(nil),     // 17: google.protobuf.Timestamp
}
var file_api_usr_invite_code_proto_depIdxs = []int32{
	17, // 0: api_usr_invite_code.UserInviteCode.meta_valid_from:type_name -> google.protobuf.Timestamp
	17, // 1: api_usr_invite_code.UserInviteCode.meta_valid_to:type_name -> google.protobuf.Timestamp
	17, // 2: api_usr_invite_code.UserInviteCode.created_at:type_name -> google.protobuf.Timestamp
	17, // 3: api_usr_invite_code.UserInviteCode.updated_at:type_name -> google.protobuf.Timestamp
	17, // 4: api_usr_invite_code.UserInviteCode.deleted_at:type_name -> google.protobuf.Timestamp
	1,  // 5: api_usr_invite_code.CreateInviteCodeReq.inviteCode:type_name -> api_usr_invite_code.UserInviteCode
	1,  // 6: api_usr_invite_code.CreateInviteCodeRes.inviteCode:type_name -> api_usr_invite_code.UserInviteCode
	1,  // 7: api_usr_invite_code.GetInviteCodeRes.inviteCode:type_name -> api_usr_invite_code.UserInviteCode
	1,  // 8: api_usr_invite_code.UpdateInviteCodeReq.inviteCode:type_name -> api_usr_invite_code.UserInviteCode
	1,  // 9: api_usr_invite_code.UpdateInviteCodeRes.inviteCode:type_name -> api_usr_invite_code.UserInviteCode
	2,  // 10: api_usr_invite_code.ListFilteredInviteCodeReq.filter:type_name -> api_usr_invite_code.UserInviteCodeFilter
	1,  // 11: api_usr_invite_code.ListFilteredInviteCodeRes.inviteCode:type_name -> api_usr_invite_code.UserInviteCode
	1,  // 12: api_usr_invite_code.ListInviteCodeRes.inviteCode:type_name -> api_usr_invite_code.UserInviteCode
	3,  // 13: api_usr_invite_code.UserInviteCodeService.CreateInviteCode:input_type -> api_usr_invite_code.CreateInviteCodeReq
	5,  // 14: api_usr_invite_code.UserInviteCodeService.GetInviteCode:input_type -> api_usr_invite_code.GetInviteCodeReq
	7,  // 15: api_usr_invite_code.UserInviteCodeService.UpdateInviteCode:input_type -> api_usr_invite_code.UpdateInviteCodeReq
	9,  // 16: api_usr_invite_code.UserInviteCodeService.DeleteInviteCode:input_type -> api_usr_invite_code.DeleteInviteCodeReq
	13, // 17: api_usr_invite_code.UserInviteCodeService.ListInviteCodes:input_type -> api_usr_invite_code.ListInviteCodeReq
	11, // 18: api_usr_invite_code.UserInviteCodeService.ListFilteredInviteCodes:input_type -> api_usr_invite_code.ListFilteredInviteCodeReq
	15, // 19: api_usr_invite_code.UserInviteCodeService.GetVersion:input_type -> api_usr_invite_code.VersionReq
	4,  // 20: api_usr_invite_code.UserInviteCodeService.CreateInviteCode:output_type -> api_usr_invite_code.CreateInviteCodeRes
	6,  // 21: api_usr_invite_code.UserInviteCodeService.GetInviteCode:output_type -> api_usr_invite_code.GetInviteCodeRes
	8,  // 22: api_usr_invite_code.UserInviteCodeService.UpdateInviteCode:output_type -> api_usr_invite_code.UpdateInviteCodeRes
	10, // 23: api_usr_invite_code.UserInviteCodeService.DeleteInviteCode:output_type -> api_usr_invite_code.DeleteInviteCodeRes
	14, // 24: api_usr_invite_code.UserInviteCodeService.ListInviteCodes:output_type -> api_usr_invite_code.ListInviteCodeRes
	12, // 25: api_usr_invite_code.UserInviteCodeService.ListFilteredInviteCodes:output_type -> api_usr_invite_code.ListFilteredInviteCodeRes
	16, // 26: api_usr_invite_code.UserInviteCodeService.GetVersion:output_type -> api_usr_invite_code.VersionRes
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_usr_invite_code_proto_init() }
func file_api_usr_invite_code_proto_init() {
	if File_api_usr_invite_code_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_usr_invite_code_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usr_invite_code_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInviteCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usr_invite_code_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInviteCodeFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usr_invite_code_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateInviteCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usr_invite_code_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateInviteCodeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usr_invite_code_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInviteCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usr_invite_code_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInviteCodeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usr_invite_code_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateInviteCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usr_invite_code_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateInviteCodeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usr_invite_code_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteInviteCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usr_invite_code_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteInviteCodeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usr_invite_code_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFilteredInviteCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usr_invite_code_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFilteredInviteCodeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usr_invite_code_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListInviteCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usr_invite_code_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListInviteCodeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usr_invite_code_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usr_invite_code_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_usr_invite_code_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_usr_invite_code_proto_goTypes,
		DependencyIndexes: file_api_usr_invite_code_proto_depIdxs,
		MessageInfos:      file_api_usr_invite_code_proto_msgTypes,
	}.Build()
	File_api_usr_invite_code_proto = out.File
	file_api_usr_invite_code_proto_rawDesc = nil
	file_api_usr_invite_code_proto_goTypes = nil
	file_api_usr_invite_code_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserInviteCodeServiceClient is the client API for UserInviteCodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserInviteCodeServiceClient interface {
	CreateInviteCode(ctx context.Context, in *CreateInviteCodeReq, opts ...grpc.CallOption) (*CreateInviteCodeRes, error)
	GetInviteCode(ctx context.Context, in *GetInviteCodeReq, opts ...grpc.CallOption) (*GetInviteCodeRes, error)
	UpdateInviteCode(ctx context.Context, in *UpdateInviteCodeReq, opts ...grpc.CallOption) (*UpdateInviteCodeRes, error)
	DeleteInviteCode(ctx context.Context, in *DeleteInviteCodeReq, opts ...grpc.CallOption) (*DeleteInviteCodeRes, error)
	ListInviteCodes(ctx context.Context, in *ListInviteCodeReq, opts ...grpc.CallOption) (UserInviteCodeService_ListInviteCodesClient, error)
	ListFilteredInviteCodes(ctx context.Context, in *ListFilteredInviteCodeReq, opts ...grpc.CallOption) (UserInviteCodeService_ListFilteredInviteCodesClient, error)
	GetVersion(ctx context.Context, in *VersionReq, opts ...grpc.CallOption) (*VersionRes, error)
}

type userInviteCodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserInviteCodeServiceClient(cc grpc.ClientConnInterface) UserInviteCodeServiceClient {
	return &userInviteCodeServiceClient{cc}
}

func (c *userInviteCodeServiceClient) CreateInviteCode(ctx context.Context, in *CreateInviteCodeReq, opts ...grpc.CallOption) (*CreateInviteCodeRes, error) {
	out := new(CreateInviteCodeRes)
	err := c.cc.Invoke(ctx, "/api_usr_invite_code.UserInviteCodeService/CreateInviteCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInviteCodeServiceClient) GetInviteCode(ctx context.Context, in *GetInviteCodeReq, opts ...grpc.CallOption) (*GetInviteCodeRes, error) {
	out := new(GetInviteCodeRes)
	err := c.cc.Invoke(ctx, "/api_usr_invite_code.UserInviteCodeService/GetInviteCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInviteCodeServiceClient) UpdateInviteCode(ctx context.Context, in *UpdateInviteCodeReq, opts ...grpc.CallOption) (*UpdateInviteCodeRes, error) {
	out := new(UpdateInviteCodeRes)
	err := c.cc.Invoke(ctx, "/api_usr_invite_code.UserInviteCodeService/UpdateInviteCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInviteCodeServiceClient) DeleteInviteCode(ctx context.Context, in *DeleteInviteCodeReq, opts ...grpc.CallOption) (*DeleteInviteCodeRes, error) {
	out := new(DeleteInviteCodeRes)
	err := c.cc.Invoke(ctx, "/api_usr_invite_code.UserInviteCodeService/DeleteInviteCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInviteCodeServiceClient) ListInviteCodes(ctx context.Context, in *ListInviteCodeReq, opts ...grpc.CallOption) (UserInviteCodeService_ListInviteCodesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UserInviteCodeService_serviceDesc.Streams[0], "/api_usr_invite_code.UserInviteCodeService/ListInviteCodes", opts...)
	if err != nil {
		return nil, err
	}
	x := &userInviteCodeServiceListInviteCodesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserInviteCodeService_ListInviteCodesClient interface {
	Recv() (*ListInviteCodeRes, error)
	grpc.ClientStream
}

type userInviteCodeServiceListInviteCodesClient struct {
	grpc.ClientStream
}

func (x *userInviteCodeServiceListInviteCodesClient) Recv() (*ListInviteCodeRes, error) {
	m := new(ListInviteCodeRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userInviteCodeServiceClient) ListFilteredInviteCodes(ctx context.Context, in *ListFilteredInviteCodeReq, opts ...grpc.CallOption) (UserInviteCodeService_ListFilteredInviteCodesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UserInviteCodeService_serviceDesc.Streams[1], "/api_usr_invite_code.UserInviteCodeService/ListFilteredInviteCodes", opts...)
	if err != nil {
		return nil, err
	}
	x := &userInviteCodeServiceListFilteredInviteCodesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserInviteCodeService_ListFilteredInviteCodesClient interface {
	Recv() (*ListFilteredInviteCodeRes, error)
	grpc.ClientStream
}

type userInviteCodeServiceListFilteredInviteCodesClient struct {
	grpc.ClientStream
}

func (x *userInviteCodeServiceListFilteredInviteCodesClient) Recv() (*ListFilteredInviteCodeRes, error) {
	m := new(ListFilteredInviteCodeRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userInviteCodeServiceClient) GetVersion(ctx context.Context, in *VersionReq, opts ...grpc.CallOption) (*VersionRes, error) {
	out := new(VersionRes)
	err := c.cc.Invoke(ctx, "/api_usr_invite_code.UserInviteCodeService/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserInviteCodeServiceServer is the server API for UserInviteCodeService service.
type UserInviteCodeServiceServer interface {
	CreateInviteCode(context.Context, *CreateInviteCodeReq) (*CreateInviteCodeRes, error)
	GetInviteCode(context.Context, *GetInviteCodeReq) (*GetInviteCodeRes, error)
	UpdateInviteCode(context.Context, *UpdateInviteCodeReq) (*UpdateInviteCodeRes, error)
	DeleteInviteCode(context.Context, *DeleteInviteCodeReq) (*DeleteInviteCodeRes, error)
	ListInviteCodes(*ListInviteCodeReq, UserInviteCodeService_ListInviteCodesServer) error
	ListFilteredInviteCodes(*ListFilteredInviteCodeReq, UserInviteCodeService_ListFilteredInviteCodesServer) error
	GetVersion(context.Context, *VersionReq) (*VersionRes, error)
}

// UnimplementedUserInviteCodeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserInviteCodeServiceServer struct {
}

func (*UnimplementedUserInviteCodeServiceServer) CreateInviteCode(context.Context, *CreateInviteCodeReq) (*CreateInviteCodeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInviteCode not implemented")
}
func (*UnimplementedUserInviteCodeServiceServer) GetInviteCode(context.Context, *GetInviteCodeReq) (*GetInviteCodeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInviteCode not implemented")
}
func (*UnimplementedUserInviteCodeServiceServer) UpdateInviteCode(context.Context, *UpdateInviteCodeReq) (*UpdateInviteCodeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInviteCode not implemented")
}
func (*UnimplementedUserInviteCodeServiceServer) DeleteInviteCode(context.Context, *DeleteInviteCodeReq) (*DeleteInviteCodeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInviteCode not implemented")
}
func (*UnimplementedUserInviteCodeServiceServer) ListInviteCodes(*ListInviteCodeReq, UserInviteCodeService_ListInviteCodesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListInviteCodes not implemented")
}
func (*UnimplementedUserInviteCodeServiceServer) ListFilteredInviteCodes(*ListFilteredInviteCodeReq, UserInviteCodeService_ListFilteredInviteCodesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListFilteredInviteCodes not implemented")
}
func (*UnimplementedUserInviteCodeServiceServer) GetVersion(context.Context, *VersionReq) (*VersionRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}

func RegisterUserInviteCodeServiceServer(s *grpc.Server, srv UserInviteCodeServiceServer) {
	s.RegisterService(&_UserInviteCodeService_serviceDesc, srv)
}

func _UserInviteCodeService_CreateInviteCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInviteCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInviteCodeServiceServer).CreateInviteCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api_usr_invite_code.UserInviteCodeService/CreateInviteCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInviteCodeServiceServer).CreateInviteCode(ctx, req.(*CreateInviteCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInviteCodeService_GetInviteCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInviteCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInviteCodeServiceServer).GetInviteCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api_usr_invite_code.UserInviteCodeService/GetInviteCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInviteCodeServiceServer).GetInviteCode(ctx, req.(*GetInviteCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInviteCodeService_UpdateInviteCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInviteCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInviteCodeServiceServer).UpdateInviteCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api_usr_invite_code.UserInviteCodeService/UpdateInviteCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInviteCodeServiceServer).UpdateInviteCode(ctx, req.(*UpdateInviteCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInviteCodeService_DeleteInviteCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInviteCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInviteCodeServiceServer).DeleteInviteCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api_usr_invite_code.UserInviteCodeService/DeleteInviteCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInviteCodeServiceServer).DeleteInviteCode(ctx, req.(*DeleteInviteCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInviteCodeService_ListInviteCodes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListInviteCodeReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserInviteCodeServiceServer).ListInviteCodes(m, &userInviteCodeServiceListInviteCodesServer{stream})
}

type UserInviteCodeService_ListInviteCodesServer interface {
	Send(*ListInviteCodeRes) error
	grpc.ServerStream
}

type userInviteCodeServiceListInviteCodesServer struct {
	grpc.ServerStream
}

func (x *userInviteCodeServiceListInviteCodesServer) Send(m *ListInviteCodeRes) error {
	return x.ServerStream.SendMsg(m)
}

func _UserInviteCodeService_ListFilteredInviteCodes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListFilteredInviteCodeReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserInviteCodeServiceServer).ListFilteredInviteCodes(m, &userInviteCodeServiceListFilteredInviteCodesServer{stream})
}

type UserInviteCodeService_ListFilteredInviteCodesServer interface {
	Send(*ListFilteredInviteCodeRes) error
	grpc.ServerStream
}

type userInviteCodeServiceListFilteredInviteCodesServer struct {
	grpc.ServerStream
}

func (x *userInviteCodeServiceListFilteredInviteCodesServer) Send(m *ListFilteredInviteCodeRes) error {
	return x.ServerStream.SendMsg(m)
}

func _UserInviteCodeService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInviteCodeServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api_usr_invite_code.UserInviteCodeService/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInviteCodeServiceServer).GetVersion(ctx, req.(*VersionReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserInviteCodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api_usr_invite_code.UserInviteCodeService",
	HandlerType: (*UserInviteCodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateInviteCode",
			Handler:    _UserInviteCodeService_CreateInviteCode_Handler,
		},
		{
			MethodName: "GetInviteCode",
			Handler:    _UserInviteCodeService_GetInviteCode_Handler,
		},
		{
			MethodName: "UpdateInviteCode",
			Handler:    _UserInviteCodeService_UpdateInviteCode_Handler,
		},
		{
			MethodName: "DeleteInviteCode",
			Handler:    _UserInviteCodeService_DeleteInviteCode_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _UserInviteCodeService_GetVersion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListInviteCodes",
			Handler:       _UserInviteCodeService_ListInviteCodes_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListFilteredInviteCodes",
			Handler:       _UserInviteCodeService_ListFilteredInviteCodes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api_usr_invite_code.proto",
}
